### ISSUE TITLE
Figure out better strategy for travis

### ISSUE THREAD

**Issue by hadley** [edzer/sfr#142]
Your current travis configure currently builds GDAL for every run - there must be a better way. @jimhester should have some ideas

(This will become increasing important as more packages add sf to their dependencies)

**Comment by edzer** [comment]
This has been discussed earlier at https://github.com/edzer/sfr/issues/107

**Comment by hadley** [comment]
That solution doesn't look quite right to me either. Hopefully Jim will have some ideas.

**Comment by mdsumner** [comment]
@hadley What is not right about it? Genuine question, just wondering what you're looking for.

**Comment by mdsumner** [comment]
I see, it's not for sf itself - mine is just for packages with a light-dependence on sf (no postgis). I'm keen to see what the right way/s are.

**Comment by edzer** [comment]
I have the [sf travis](https://travis-ci.org/edzer/sfr) now down to around 14 mins, by
* installing proj, gdal and geos from ppa:ubuntugis (takes 30 sec); we need this otherwise gdal is too old
* installing postgis from source (this takes around 1 min.); although it is there, we can't install the postgis from ppa:ubuntugis, it somehow conflicts with what travis has (it's no problem on my machine, or a trusty docker image; this may be resolved over time)

The majority of these 14 mins really goes into the setup and installing all the dependent R pacakges.

A minimal package [depending on sf](https://travis-ci.org/edzer/sf_dep) now requires 3 mins on travis, and needs the additional three lines in [.travis.yml](https://github.com/edzer/sf_dep/blob/master/.travis.yml) to install system requirements proj, gdal, geos, and udunits2.

**Comment by hadley** [comment]
Awesome!  But I'm not sure why the dependencies are getting built each time - they should be included in the cache.

**Comment by dblodgett-usgs** [comment]
Kudos for sf_dep!!! Need to promote awareness of that a bit.
