### ISSUE TITLE
Install and udunits2

### ISSUE THREAD

**Issue by zross** [edzer/sfr#171]
Hi Edzer, just letting you know that I was stuck on installation of sf on a Mac because udunits2 was failing to install. It took me a while to find your page https://github.com/edzer/units/issues/1 and the mentions of `brew install udunits` -- might be worth mentioning on the main readme if it's an issue others are having. Thanks for your hard work on this!!

**Comment by edzer** [comment]
Thanks Zev; I'm not sure whether I understand the R Mac ecosystem, but I decided to allow for a dependency on `units` since both `units` and `udunits2` have binary mac (and windows) distributions, meaning there is no need for brew installs. 

Or do you by default install everything from source? In that case, I'd say that resolving the system requirements is a reasonable thing to assume the user: you'd have to do that for `sf` as well (proj, geos, gdal).
