### ISSUE TITLE
xlim doesn't appear to be working

### ISSUE THREAD

**Issue by cpsievert** [edzer/sfr#267]
This works as expected:

```r
library(sf)
library(mapdata)

m <- st_as_sf(maps::map('world', plot = FALSE, fill = TRUE))

plot(m, axes = TRUE)
```

<img width="657" alt="screen shot 2017-03-23 at 2 52 32 pm" src="https://cloud.githubusercontent.com/assets/1365941/24267872/abd7fa78-0fd9-11e7-868d-e0dd1281728b.png">

However, specifying any `xlim` within the bbox seems to result the wrong axis limits. The image below was produced using my default graphics device, but (oddly enough) in RStudio, `xlim` doesn't seem to change anything (i.e., I get the original image).

```r
st_bbox(m)
#>      xmin       ymin       xmax       ymax 
#> -180.00000  -85.19218  190.27084   83.59961 

# I've tried these, both give same result
plot(m, xlim = c(-20, 20), axes = TRUE)
plot(m, xlim = c(-50, 50), axes = TRUE)
```

<img width="749" alt="screen shot 2017-03-23 at 3 01 43 pm" src="https://cloud.githubusercontent.com/assets/1365941/24267880/b0157d4a-0fd9-11e7-95de-75b4d360aa39.png">

**Comment by edzer** [comment]
No: you'd need to set the plotting region very high and narrow to get that; if it is square, as in your plots, it will look at what y is for xlim=c(-20,20), will find that y ranges from -90,90 (because you didn't set it), and then take that as ylim, and find the corresponding xlim.

I got the plot below with
```r
> png("/tmp/m.png", width=200, height = 400)
> plot(m, xlim = c(-20, 20), axes = TRUE)
> dev.off()
```
![m](https://cloud.githubusercontent.com/assets/520851/24326295/b379dc0a-11ab-11e7-84eb-678f86b8910a.png)
