### ISSUE TITLE
Allow retention of attributes with GEOS functions (intersect, union, etc)

### ISSUE THREAD

**Issue by ateucher** [edzer/sfr#89]
As discussed briefly [here](https://github.com/tim-salabim/rspatial/issues/5) it would be great to have versions of `st_intersection`, `st_union` etc that return objects of class `sf` and retain attributes from the inputs (similar to analagous `Spatial` methods in the raster package).

**Comment by edzer** [comment]
This should be fixed by https://github.com/edzer/sfr/commit/a871248862d3db5a89a5e728913c02470b08d380 , file geom.R, line 299 and further. What is returned is not the full set of n x m possibilities, but only those with non-empty geometries, along with a matrix of indexes of the original entries in `x` and `y` as an attribute.

**Comment by ateucher** [comment]
Fantastic, thanks! I won't be able to test it properly for the next week or so unfortunately...
